# coding: utf-8

"""
    Insignia Vendor Parts API

    ## Overview / Purpose
The Insignia Group Vendor Parts API allows retrieval of the Parts that are available for a 3rd Party Vendors "VehicleID".
  * Limited support has been added for MOTOR using the DaasSandbox.

## What does this API do?
This API works by filtering our available Parts by the specified Vendors "VehicleID". For instance, calling these endpoints with MOTOR VehicleID #61040 (2010 Honda Civic EX) would return the Parts for our AppID #5344  (2010 Honda Civic Coupe EX).

## Intended Audience
The intended audience would be interested in displaying the Parts available for a particular Vehecile, or Application.

## Authentication Required
Hash-based Message Authentication Code (HMAC) using an ApiKey and SHA-256 hashing is required in the Authentication HTTP Header. This requires the caller to be an Insignia Dealer with a PublicKey and a shared PrivateKey configured.
  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: customerservice@insigniagroup.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from GroupedPart.clsGroupedPart import GroupedPart  # noqa: E501
from swagger_client.rest import ApiException


class TestGroupedPart(unittest.TestCase):
    """GroupedPart unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupedPart(self):
        """Test GroupedPart"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.clsGroupedPart.GroupedPart()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
